#pragma once

#include <stdint.h>

 
// SHARED PROTOCOL DEFINITIONS
// Used by both Transmitter (Node A) and Receiver (Node B).
// Implements ChaCha20-Poly1305 authenticated encryption with
// a pre-shared 256-bit master key (PSK).


// Pre-Shared Master Key (256-bit / 32 bytes)
//
// Both nodes must carry the SAME key compiled into their firmware.
// Replace these placeholder bytes with your own secret values
// before deploying to hardware.
//
// Used as the ChaCha20-Poly1305 key material for DATA packets.
// The key is NEVER transmitted over the wire.
const uint8_t MASTER_PSK[32] = {
  0xA1, 0x3C, 0x7F, 0x04, 0xE8, 0x92, 0x5B, 0xD6,
  0x3A, 0xFF, 0x01, 0x88, 0x4D, 0x62, 0xC0, 0x19,
  0x77, 0x2E, 0xB3, 0x55, 0x0C, 0xAD, 0xF1, 0x39,
  0x6B, 0x84, 0xE0, 0x27, 0x93, 0x5A, 0x1D, 0xCC
};


// Packet type identifiers
//
// Carried in the first byte of every frame so the receiver can
// dispatch the correct handler without reading further bytes.
const uint8_t PACKET_TYPE_HELLO = 0x01; // Handshake frame  — carries the session nonce
const uint8_t PACKET_TYPE_DATA  = 0x02; // Data frame       — carries an encrypted note packet


// Frame size constants
const uint8_t HELLO_NONCE_SIZE   = 12u; // ChaChaPoly IV length (IETF 96-bit nonce)
const uint8_t AUTH_TAG_SIZE      = 16u; // Full Poly1305 tag length (used internally)
const uint8_t TRUNCATED_MAC_SIZE =  8u; // Bytes of MAC actually transmitted (first 8 of 16)
// Plaintext payload of a DATA packet (encrypted portion):
//   [0] note_index  (uint16_t) — index into the receiver's frequency dictionary
//   [1] duration_ms (uint16_t) — note duration in milliseconds (direct, no encoding)
const uint8_t DATA_PAYLOAD_SIZE  = 4u;  // sizeof(uint16_t) * 2

// Synchronisation preamble — two bytes sent immediately before every DataPacket.
// The receiver scans for this pattern to re-lock onto the frame boundary
// after a noise burst.  Using two distinct bytes reduces the false-sync rate
// compared to a single repeated byte.
const uint8_t SYNC_BYTE_1 = 0xAA;
const uint8_t SYNC_BYTE_2 = 0x55;


// HELLO packet
//
// Sent by TX at the start of every melody session to deliver a
// fresh 12-byte nonce to RX.  The nonce is generated by the
// CSPRNG (ChaCha20 seeded with hardware entropy) and is unique
// per session, making each DATA-packet ciphertext unique even
// if the plaintext repeats across sessions.
//
// Wire layout (13 bytes total):
//   Byte  0     : packet_type (0x01)
//   Bytes 1–12  : nonce[12]
#pragma pack(push, 1)
struct HelloPacket {
  uint8_t packet_type;             // Always PACKET_TYPE_HELLO (0x01)
  uint8_t nonce[HELLO_NONCE_SIZE]; // 96-bit session nonce for ChaChaPoly
};
#pragma pack(pop)


// DATA packet
//
// Carries one encrypted note (note_index + duration_encoded) authenticated
// with a 16-byte Poly1305 MAC tag.  seq_num lives in the open header so
// both nodes can independently compute the per-packet nonce:
//   packetNonce = sessionNonce XOR (0x00…0 || seq_num)
// without first decrypting the payload.
//
// Wire layout (15 bytes, preceded by 2 sync bytes = 17 bytes on the wire):
//   Byte  0     : packet_type (0x02)  ─┬─ AAD (3 bytes authenticated,
//   Bytes 1–2   : seq_num (uint16_t)  ─┘     but NOT encrypted)
//   Bytes 3–6   : payload[2] uint16_t — ChaCha20 ciphertext (note_index, duration_ms)
//   Bytes 7–14  : mac[8]              — first 8 bytes of Poly1305 tag
//
// Security property: any bit-flip in packet_type OR either seq_num byte causes
// MAC verification to fail and the packet is discarded (NACK sent).
#pragma pack(push, 1)
struct DataPacket {
  uint8_t  packet_type;               // Always PACKET_TYPE_DATA (0x02)  ─┬─ plaintext AAD
  uint16_t seq_num;                   // 16-bit sequence number (little-endian) ─┘
  uint16_t payload[2];                // Encrypted: [note_index, duration_ms]
  uint8_t  mac[TRUNCATED_MAC_SIZE];   // First 8 bytes of Poly1305 tag
};
#pragma pack(pop)


// Service bytes (feedback channel)
const uint8_t ACK_BYTE  = 0x06; // Positive acknowledgement (DATA packet authenticated)
const uint8_t NACK_BYTE = 0x15; // Negative acknowledgement (MAC mismatch — resend)


// Note encoding helpers

// REST / pause sentinel.
// TX sends this index to instruct RX to silence the buzzer.
const uint8_t REST_INDEX = 255;

// Duration is stored directly as uint16_t milliseconds in the payload—no
// encoding step required now that payload fields are 16-bit.

// Stop-and-Wait ARQ timing
const uint32_t ACK_TIMEOUT_MS = 50UL; // Max ms to wait for ACK before retransmitting
const uint8_t  MAX_RETRIES    = 3u;   // Retransmission limit before skipping the note

// UART configuration 
const uint16_t BAUD_RATE = 9600;
