// TRANSMITTER (Node A) — "The Conductor"
// Flash this sketch onto the TX Arduino Nano.
//
// Responsibilities:
//   - Read the start button (with millis-based debounce on D2).
//   - Walk through the Super Mario melody array packet by packet.
//   - formAndSendPacket(): full crypto pipeline (key gen → encrypt → checksum → send).
//   - Stop-and-Wait ARQ: after every SEND wait up to ACK_TIMEOUT_MS (50 ms) for ACK.
//     ACK  → advance melody (melodyIndex++, seqNum++).
//     NACK or timeout → retransmit the SAME packet with the SAME seqNum.
 

#include "transmitter.h"
#include <LiquidCrystal_AIP31068_I2C.h>

 
// CONSTANTS
 

// Total number of notes/pauses in the stored melody.
static const uint8_t MELODY_LENGTH = 81;

 
// MELODY DATA  (Star Wars — Imperial March)
//
// Generated by tools/midi_to_cpp.py from The_Imperial_March-Star_Wars.mid
// Column 0: note index (0-20 = C4..G#5, 255 = REST/pause)
// Column 1: duration in milliseconds (uint16_t; values may exceed 255)
 
static const uint16_t melody[MELODY_LENGTH][2] = {
    {255, 2749},  // Pause,  2749 ms
    {  7,  133},  // G4,      133 ms
    {255, 4687},  // Pause,  4687 ms
    {  7,  535},  // G4,      535 ms
    {  7,  535},  // G4,      535 ms
    {  7,  535},  // G4,      535 ms
    {  3,  401},  // D#4,     401 ms
    { 10,  133},  // A#4,     133 ms
    {  7,  535},  // G4,      535 ms
    {  3,  401},  // D#4,     401 ms
    { 10,  133},  // A#4,     133 ms
    {  7, 1071},  // G4,     1071 ms
    { 14,  535},  // D5,      535 ms
    { 14,  535},  // D5,      535 ms
    { 14,  535},  // D5,      535 ms
    { 15,  401},  // D#5,     401 ms
    { 10,  133},  // A#4,     133 ms
    {  6,  535},  // F#4,     535 ms
    {  3,  401},  // D#4,     401 ms
    { 10,  133},  // A#4,     133 ms
    {  7, 1071},  // G4,     1071 ms
    { 19,  535},  // G5,      535 ms
    {  7,  401},  // G4,      401 ms
    {  7,  133},  // G4,      133 ms
    { 19,  535},  // G5,      535 ms
    { 18,  401},  // F#5,     401 ms
    { 17,  133},  // F5,      133 ms
    { 16,  133},  // E5,      133 ms
    { 15,  133},  // D#5,     133 ms
    { 16,  133},  // E5,      133 ms
    {255,  401},  // Pause,   401 ms
    {  8,  267},  // G#4,     267 ms
    { 13,  535},  // C#5,     535 ms
    { 12,  401},  // C5,      401 ms
    { 11,  133},  // B4,      133 ms
    { 10,  133},  // A#4,     133 ms
    {  9,  133},  // A4,      133 ms
    { 10,  133},  // A#4,     133 ms
    {255,  401},  // Pause,   401 ms
    {  3,  267},  // D#4,     267 ms
    {  6,  535},  // F#4,     535 ms
    {  3,  401},  // D#4,     401 ms
    {  6,  133},  // F#4,     133 ms
    { 10,  535},  // A#4,     535 ms
    {  7,  401},  // G4,      401 ms
    { 10,  133},  // A#4,     133 ms
    { 14, 1071},  // D5,     1071 ms
    { 19,  535},  // G5,      535 ms
    {  7,  401},  // G4,      401 ms
    {  7,  133},  // G4,      133 ms
    { 19,  535},  // G5,      535 ms
    { 18,  401},  // F#5,     401 ms
    { 17,  133},  // F5,      133 ms
    { 16,  133},  // E5,      133 ms
    { 15,  133},  // D#5,     133 ms
    { 16,  133},  // E5,      133 ms
    {255,  401},  // Pause,   401 ms
    {  8,  267},  // G#4,     267 ms
    { 13,  535},  // C#5,     535 ms
    { 12,  401},  // C5,      401 ms
    { 11,  133},  // B4,      133 ms
    { 10,  133},  // A#4,     133 ms
    {  9,  133},  // A4,      133 ms
    { 10,  133},  // A#4,     133 ms
    {255,  401},  // Pause,   401 ms
    {  3,  267},  // D#4,     267 ms
    {  6,  535},  // F#4,     535 ms
    {  3,  401},  // D#4,     401 ms
    { 10,  133},  // A#4,     133 ms
    {  7,  535},  // G4,      535 ms
    {  3,  401},  // D#4,     401 ms
    { 10,  133},  // A#4,     133 ms
    {  7, 1071},  // G4,     1071 ms
    {255, 4285},  // Pause,  4285 ms
    {  7,  535},  // G4,      535 ms
    {  7,  267},  // G4,      267 ms
    {  7,  133},  // G4,      133 ms
    {  7,  133},  // G4,      133 ms
    {  7,  267},  // G4,      267 ms
    {  7,  133},  // G4,      133 ms
    {  7,   20},  // G4,       20 ms
};

 
// HARDWARE OBJECTS
 

// I2C LCD: 16 columns × 2 rows, Aip31068-compatible controller.
static LiquidCrystal_AIP31068_I2C lcd(TX_LCD_ADDR, TX_LCD_COLS, TX_LCD_ROWS);

 
// RUNTIME STATE
 

static TxState  currentState  = TxState::IDLE;
static uint8_t  melodyIndex   = 0;   // Current position within noteIndices[]
static uint8_t  seqNum        = 0;   // Packet sequence number (0–255, wraps)
static uint8_t  retryCount    = 0;   // Consecutive retransmission counter (shown on display)
static uint8_t  lastChecksum  = 0;   // Checksum of the last sent packet (internal only)
static uint32_t ackWaitStart  = 0;   // Timestamp (ms) when WAITING_ACK began

// Pending packet snapshot — allows retransmission without re-reading melody arrays.
static uint8_t  pendingNoteIndex    = 0;
static uint16_t pendingNoteDuration = 0;   // Full duration in milliseconds

// Timestamp (ms) when WAIT_BETWEEN_NOTES state began.
static uint32_t noteWaitStart = 0;

// Debounce state (millis-based) 
// INPUT_PULLUP wiring: idle = HIGH, pressed = LOW.
static bool     btnLastRawState = HIGH; // Raw digitalRead from the previous call
static bool     btnStableState  = HIGH; // Debounce-confirmed stable state
static uint32_t btnLastChangeMs = 0;    // Time of the last raw state change

 
// BUTTON HELPER — millis-based debounce
// Returns true exactly once per physical button press (falling-edge detection).
// Must be called every iteration of loop() to accumulate timing correctly.
 
bool readButtonPress() {
  // Cast to bool: LOW = 0 = false, HIGH = 1 = true (INPUT_PULLUP logic).
  const bool rawReading = (digitalRead(TX_BUTTON_PIN) != LOW);

  // Any change in the raw signal resets the stability timer.
  if (rawReading != btnLastRawState) {
    btnLastChangeMs = millis();
    btnLastRawState = rawReading;
  }

  // Promote the raw reading to the stable state only after DEBOUNCE_DELAY_MS
  // of continuous stability — this rejects contact-bounce glitches.
  if ((millis() - btnLastChangeMs) >= DEBOUNCE_DELAY_MS) {
    if (rawReading != btnStableState) {
      btnStableState = rawReading;
      // Falling edge on INPUT_PULLUP line = operator pressed the button.
      if (btnStableState == false) {
        return true;
      }
    }
  }

  return false;
}

 
// PACKET HELPERS
 

uint8_t generateDynamicKey(uint8_t seqNumber) {
  // The key changes with every packet so two identically-pitched notes appear
  // as different ciphertext bytes in the channel — replay-attack mitigation.
  // K_dynamic = SECRET_KEY ^ seq_num
  return SECRET_KEY ^ seqNumber;
}

uint8_t calculateChecksum(const uint8_t packet[PACKET_SIZE]) {
  // Checksum is computed AFTER encryption so it covers the full ciphertext
  // frame, protecting it against bit-flip corruption in the noisy channel.
  // CHK = B0 ^ B1 ^ B2 ^ B3
  return packet[PACKET_IDX_START]
       ^ packet[PACKET_IDX_NOTE]
       ^ packet[PACKET_IDX_DURATION]
       ^ packet[PACKET_IDX_SEQ];
}

void sendPacket(uint8_t noteIndex, uint16_t noteDurationMs, uint8_t seqNumber) {
  uint8_t packet[PACKET_SIZE];
  const uint8_t key = generateDynamicKey(seqNumber);

  // Encode duration into one byte: 1 unit = DURATION_UNIT_MS ms.
  // Capped at 255 to stay within uint8_t (covers up to 5 100 ms).
  const uint8_t encodedDuration = static_cast<uint8_t>(
      min(static_cast<uint16_t>(255u),
          static_cast<uint16_t>(noteDurationMs / DURATION_UNIT_MS))
  );

  // Step 1 — Assemble the frame with encrypted payload bytes.
  // Both payload fields are XOR-encrypted: C = M ^ K_dynamic
  packet[PACKET_IDX_START]    = START_MARKER;
  packet[PACKET_IDX_NOTE]     = noteIndex       ^ key;
  packet[PACKET_IDX_DURATION] = encodedDuration ^ key;
  packet[PACKET_IDX_SEQ]      = seqNumber;

  // Step 2 — Compute checksum over the already-encrypted bytes.
  packet[PACKET_IDX_CHECKSUM] = calculateChecksum(packet);
  lastChecksum = packet[PACKET_IDX_CHECKSUM];

  // Step 3 — Transmit all 5 bytes via hardware UART.
  Serial.write(packet, PACKET_SIZE);
}

// formAndSendPacket — high-level crypto pipeline entry point
//
// Workflow (matches the spec from 05_encryption_approach.instructions.md):
//   1. Store plain-text payload as the pending retransmit snapshot.
//   2. Generate K_dynamic = SECRET_KEY ^ seqNum  ← replay-attack mitigation.
//   3. Encrypt: C_note = note_idx ^ K_dynamic
//               C_dur  = duration_ms ^ K_dynamic
//   4. Assemble 5-byte packet: [0xAA | C_note | C_dur | seqNum | CHK].
//   5. Compute CHK = B0 ^ B1 ^ B2 ^ B3  (over ciphertext, not plaintext).
//   6. Transmit via Serial.write().
void formAndSendPacket(uint8_t note_idx, uint16_t duration_ms) {
  // Snapshot the plain-text payload so the FSM can retransmit on NACK
  // without re-reading the melody arrays.
  pendingNoteIndex    = note_idx;
  pendingNoteDuration = duration_ms;

  // Delegate to sendPacket which owns the full assemble+encrypt+send pipeline.
  sendPacket(note_idx, duration_ms, seqNum);
}

 
// DISPLAY HELPER
// Updates the LCD only when explicitly called — never in a busy-loop.
// Row 0: FSM state label.
// Row 1: current sequence number + last checksum in hex.
 
void updateTxDisplay(TxState state, uint8_t seqNumber, uint8_t retries) {
  lcd.clear();

  // Row 0: packet number + retry counter
  // Example: "PKT:5  RTY:2" — gives operator live ARQ visibility.
  lcd.setCursor(0, 0);
  lcd.print("PKT:");
  lcd.print(seqNumber);
  lcd.print("  RTY:");
  lcd.print(retries);

  // Row 1: FSM state label
  lcd.setCursor(0, 1);
  switch (state) {
    case TxState::IDLE:               lcd.print("IDLE");      break;
    case TxState::SENDING:            lcd.print("SENDING");   break;
    case TxState::WAITING_ACK:        lcd.print("WAIT ACK");  break;
    case TxState::WAIT_BETWEEN_NOTES: lcd.print("WAIT NOTE"); break;
  }
}

// ENTROPY POOL  (TX variant — includes human-timing jitter from button press)

// Pulse counter incremented by the ring oscillator ISR on pin 2 (INT0).
// volatile prevents the compiler from caching the value in a register.
static volatile uint32_t s_ringOscPulses = 0;
static void onRingOscPulse() { ++s_ringOscPulses; }

// mixEntropy — one step of the cryptographic sponge.
// Rotates the pool left by 1 bit, then XOR-folds in new entropy bits.
// Left-rotation ensures every bit of the pool eventually influences all others.
static inline uint32_t mixEntropy(uint32_t pool, uint32_t bits) {
  return ((pool << 1u) | (pool >> 31u)) ^ bits;
}

// generateEntropyPool (TX) — fills outputSeed[32] with 256 bits of entropy.
// The 32-byte output is structured as 8 independent 32-bit words.
// Each word is produced by a fresh pass over ALL seven hardware sources,
// ensuring that even if one source is biased in a given iteration, the
// others compensate through the rotate-XOR mixing chain.
//
// Total execution time: 8 iterations × 2 ms gate ≈ 16 ms (one-shot only).
void generateEntropyPool(uint8_t* outputSeed) {
  // SRAM base: 64 uninitialised bytes starting at 0x0100 on ATmega328P.
  // Each word consumes a distinct 8-byte slice so the slices never repeat.
  const uint8_t* sramBase = reinterpret_cast<const uint8_t*>(0x0100);

  for (uint8_t wordIndex = 0; wordIndex < 8u; ++wordIndex) {
    uint32_t pool = 0;

    // Source 1: Ring oscillator gate (pin 2, INT0) — fresh 2 ms window per word.
    s_ringOscPulses = 0;
    attachInterrupt(digitalPinToInterrupt(ENTROPY_RING_OSC_PIN),
                    onRingOscPulse, RISING);
    delay(2);
    detachInterrupt(digitalPinToInterrupt(ENTROPY_RING_OSC_PIN));
    pool = mixEntropy(pool, s_ringOscPulses);

    // Source 2: SRAM chaos — 8 unique bytes per word (slice: wordIndex*8 .. +7).
    for (uint8_t i = 0; i < 8u; ++i) {
      pool = mixEntropy(pool, sramBase[wordIndex * 8u + i]);
    }

    // Source 3: On-die temperature ADC (channel 8, 1.1 V ref) — 8 LSBs per word.
    {
      const uint8_t savedAdmux = ADMUX;
      ADMUX   = _BV(REFS1) | _BV(REFS0) | _BV(MUX3);  // 0xC8
      ADCSRA |= _BV(ADEN);
      // Discard first conversion after reference change
      ADCSRA |= _BV(ADSC); while (ADCSRA & _BV(ADSC)) {}
      uint8_t adcEntropy = 0;
      for (uint8_t i = 0; i < 8u; ++i) {
        ADCSRA |= _BV(ADSC); while (ADCSRA & _BV(ADSC)) {}
        adcEntropy = static_cast<uint8_t>((adcEntropy << 1u) | (ADCL & 0x01u));
      }
      pool  = mixEntropy(pool, adcEntropy);
      ADMUX = savedAdmux;
    }

    // Source 4: TCNT1 timer jitter — unique value at each iteration boundary.
    pool = mixEntropy(pool, static_cast<uint32_t>(TCNT1));

    // Source 5: A0 white noise generator — 8 LSBs per word.
    {
      uint8_t a0Entropy = 0;
      for (uint8_t i = 0; i < 8u; ++i) {
        a0Entropy = static_cast<uint8_t>(
            (a0Entropy << 1u) | (static_cast<uint8_t>(analogRead(A0)) & 0x01u)
        );
      }
      pool = mixEntropy(pool, a0Entropy);
    }

    // Source 6: Human-timing jitter (TX only) — micros() drifts between iterations.
    pool = mixEntropy(pool, micros());

    // Source 7: Arduino software PRNG (obfuscation layer).
    pool = mixEntropy(pool, static_cast<uint32_t>(random()));

    // Write the 32-bit word into the output seed as 4 bytes (little-endian).
    outputSeed[wordIndex * 4u + 0u] = static_cast<uint8_t>(pool);
    outputSeed[wordIndex * 4u + 1u] = static_cast<uint8_t>(pool >>  8u);
    outputSeed[wordIndex * 4u + 2u] = static_cast<uint8_t>(pool >> 16u);
    outputSeed[wordIndex * 4u + 3u] = static_cast<uint8_t>(pool >> 24u);
  }
}

 
// ARDUINO ENTRY POINTS
 

void tx_setup() {
  // UART: 9600 8N1 — matches protocol specification and SimulIDE oscilloscope.
  Serial.begin(BAUD_RATE);

  // Button: internal pull-up keeps the line HIGH until the button pulls it LOW.
  pinMode(TX_BUTTON_PIN, INPUT_PULLUP);

  // I2C LCD (Aip31068 compatible, address 0x27).
  lcd.init();
  // lcd.backlight();

  currentState = TxState::IDLE;
  updateTxDisplay(currentState, seqNum, retryCount);
}

void tx_loop() {
  // readButtonPress() must run every iteration so the debounce timer
  // keeps accumulating even when the FSM is not in IDLE.
  const bool buttonPressed = readButtonPress();

  switch (currentState) {

    case TxState::IDLE:
      // Wait for the operator to press the start button before transmitting.
      if (buttonPressed) {
        melodyIndex = 0;
        seqNum      = 0;
        retryCount  = 0;  // Fresh start — reset the retry display counter.

        // ENTROPY TEST (remove after validation)
        // Harvest the nonce at the exact microsecond of the button press so
        // human-timing jitter is maximally folded into the pool (Source 6).
    //  const uint32_t testNonce = generateEntropyPool();
    //  lcd.clear();
    //  lcd.setCursor(0, 0);
    //  lcd.print("TX KEY:");
    //  lcd.setCursor(0, 1);
    //  lcd.print(testNonce, HEX);  // e.g. "A3F1C72B"
    //  delay(3000);                // Hold result on screen for 3 s
        // END ENTROPY TEST

        currentState = TxState::SENDING;
        updateTxDisplay(currentState, seqNum, retryCount);
      }
      break;

    case TxState::SENDING:
      if (melodyIndex >= MELODY_LENGTH) {
        // All notes delivered — melody is complete.
        currentState = TxState::IDLE;
        updateTxDisplay(currentState, seqNum, retryCount);
        break;
      }
      // Build, encrypt, and transmit the current note.
      // seqNum is NOT yet incremented — it advances only on ACK so that
      // every retransmission of the same note reuses the same key.
      formAndSendPacket(
          static_cast<uint8_t>(melody[melodyIndex][0]),
          melody[melodyIndex][1]
      );
      ackWaitStart = millis(); // Open the ACK receive window (50 ms).
      currentState = TxState::WAITING_ACK;
      updateTxDisplay(currentState, seqNum, retryCount);
      break;

    case TxState::WAITING_ACK:
      if (Serial.available() > 0) {
        const uint8_t response = static_cast<uint8_t>(Serial.read());

        if (response == ACK_BYTE) {
          // ACK: packet intact → enter the inter-note pause before advancing.
          // melodyIndex is NOT incremented here — WAIT_BETWEEN_NOTES still
          // needs melody[melodyIndex][1] to determine how long to pause.
          retryCount    = 0;
          noteWaitStart = millis();
          currentState  = TxState::WAIT_BETWEEN_NOTES;
          updateTxDisplay(currentState, seqNum, retryCount);

        } else if (response == NACK_BYTE) {
          // NACK: RX detected corruption → retransmit the SAME packet.
          retryCount++;
          formAndSendPacket(pendingNoteIndex, pendingNoteDuration);
          ackWaitStart = millis();
          updateTxDisplay(currentState, seqNum, retryCount);
        }
        // Any other byte (noise on the feedback line) is silently ignored.

      } else if ((millis() - ackWaitStart) >= ACK_TIMEOUT_MS) {
        // Timeout: no response within 50 ms → channel or ACK was lost.
        // Retransmit the SAME packet with the SAME seqNum.
        retryCount++;
        formAndSendPacket(pendingNoteIndex, pendingNoteDuration);
        ackWaitStart = millis();
        updateTxDisplay(currentState, seqNum, retryCount);
      }
      break;

    case TxState::WAIT_BETWEEN_NOTES:
      // Hold for the duration of the just-acknowledged note/pause before
      // sending the next packet. This preserves melody timing exactly,
      // including long pauses that exceed a single uint8_t in milliseconds.
      if ((millis() - noteWaitStart) >= melody[melodyIndex][1]) {
        melodyIndex++;
        seqNum++;   // Advance together with melodyIndex so keys stay in sync.
        retryCount   = 0;
        currentState = TxState::SENDING;
        updateTxDisplay(currentState, seqNum, retryCount);
      }
      break;
  }
}

// Arduino sketch entry points 
void setup() { tx_setup(); }
void loop()  { tx_loop();  }
